# Generated by Django 5.1.7 on 2025-03-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_type',
            field=models.CharField(choices=[('Future', 'Future Student'), ('Current', 'Current Student'), ('Alumni', 'Alumni Student'), ('None', 'Neither')], default='None', max_length=50),
        ),
    ]
