# Generated by Django 5.1.7 on 2025-03-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='restrict_cohorts',
            field=models.BooleanField(default=False),
        ),
    ]
