# Generated by Django 5.1.7 on 2025-03-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_restrict_cohorts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='restrict_cohorts',
        ),
    ]
